Restrict publish workflow to main branch.

diff --git a/.github/workflows/nuget-publish.yml b/.github/workflows/nuget-publish.yml
--- a/.github/workflows/nuget-publish.yml
+++ b/.github/workflows/nuget-publish.yml
@@ -3,7 +3,7 @@
 #
 # Purpose:
 #   This workflow builds, tests, and publishes a .NET library to NuGet when a new release is 
-#   published in the main branch or manually triggered.
+#   published and the tag is associated with the main branch.
 #
 # Prerequisites:
 #   - The release tag must follow the format: v<major>.<minor>.<patch> (e.g.,  v1.2.3).
@@ -15,6 +15,8 @@ name: NuGet Publish
 on:
   release:
     types: [published]
+    branches:
+      - main
 
   workflow_dispatch:
 
@@ -23,6 +25,21 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Determine version number
+        run: |
+          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
+            RELEASE_TAG=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
+          else
+            RELEASE_TAG=${GITHUB_REF_NAME}
+          fi
+
+          VERSION=$(echo "$RELEASE_TAG" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
+          if [ -z "$VERSION" ]; then
+            echo "Error: Failed to determine version. Ensure the tag follows the format v<major>.<minor>.<patch>."
+            exit 1
+          fi
+          echo "VERSION=$VERSION" >> $GITHUB_ENV
+
       - name: Checkout repository
         uses: actions/checkout@v6
 
@@ -30,21 +47,6 @@ jobs:
         uses: actions/setup-dotnet@v5
         with:
           dotnet-version: 10.0.x
-
-      - name: Get version
-        run: |
-          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
-            RELEASE=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
-          else
-            RELEASE=${GITHUB_REF_NAME}
-          fi
-
-          VERSION=$(echo "$RELEASE" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
-          if [ -z "$VERSION" ]; then
-            echo "Error: Failed to determine version. Ensure the tag follows the format v<major>.<minor>.<patch>."
-            exit 1
-          fi
-          echo "VERSION=$VERSION" >> $GITHUB_ENV
 
       - name: Restore dependencies
         run: dotnet restore
